// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz5upePenxMA4MH3yY4q2f8ZX3jwg0se0',
    appId: '1:785040075286:web:28913eb23dff295b306337',
    messagingSenderId: '785040075286',
    projectId: 'ayna-chat',
    authDomain: 'ayna-chat.firebaseapp.com',
    storageBucket: 'ayna-chat.appspot.com',
    measurementId: 'G-KKZ1YZKYE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzu4NbilX2YHXEyBtrB8N3A6mt4sNrKmc',
    appId: '1:785040075286:android:4e5f3fa7a92b40f4306337',
    messagingSenderId: '785040075286',
    projectId: 'ayna-chat',
    storageBucket: 'ayna-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJZ90eVlyhGBn2CpA8ifTYnva0SBhzipU',
    appId: '1:785040075286:ios:59df2033fd7004c5306337',
    messagingSenderId: '785040075286',
    projectId: 'ayna-chat',
    storageBucket: 'ayna-chat.appspot.com',
    iosBundleId: 'com.example.aynaChat',
  );
}
